image: jonaskello/docker-and-compose:1.12.1-1.8.0

services:
  - docker:1.12.1-dind

stages:
#  - build
  - test
#  - deploy
#  - fixture

Test Dev:
  stage: test
  environment: test
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.test.yml -p api-tests run --rm functional-tests
  tags:
    - docker