image: jonaskello/docker-and-compose:1.12.1-1.8.0

services:
  - docker:1.12.1-dind

stages:
  - build

Build web-server:
  stage: build
  environment: build
  script:
  	- docker build web-server
  tags:
    - docker

Build ci-image:
  stage: build
  environment: build
  script:
  	- docker build ci-image
  tags:
    - docker